### ISSUE TITLE
bro me wage awilla stop wenwa 

### ISSUE THREAD

**Issue by maliya93** [CryptChef/nft-toolbox#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [Google Cromei]
 - Version [Version 100.0.4896.60 (Official Build) (64-bit)]

**Additional context**
![2022-04-01_22-47-41](https://user-images.githubusercontent.com/102823879/161311364-b8ff5c36-336b-49ab-82aa-f970499a2571.png)

**Comment by maliya93** [comment]
![2022-04-01_23-28-24](https://user-images.githubusercontent.com/102823879/161317916-1604d816-3158-412a-a96e-7db279a1b21c.png)

**Comment by maliya93** [comment]
update 
![2022-04-02_12-52-55](https://user-images.githubusercontent.com/102823879/161371999-8d474781-281d-4fcc-a983-d3bf4180bfc1.png)

**Comment by maliya93** [comment]
image file ak access denied wenwa

**Comment by maliya93** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [Win 10]
> * Browser [Google Cromei]
> * Version [Version 100.0.4896.60 (Official Build) (64-bit)]
> 
> **Additional context** Add any other context about the problem here. ![2022-04-01_22-47-41](https://user-images.githubusercontent.com/102823879/161311364-b8ff5c36-336b-49ab-82aa-f970499a2571.png)

**Comment by dewmal** [comment]
responsed via phone.

the solution is,

1. Change Run the program as  an Administrator
![image](https://user-images.githubusercontent.com/499015/162167581-aef30066-fdbd-4fa3-95dd-622e3018524a.png)
2. Use Powershell instead of CMD to run the command.
